# Generated by Django 5.0.6 on 2024-07-04 16:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Page",
            new_name="Topics",
        ),
    ]
