# Generated by Django 5.0.6 on 2024-07-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_rename_page_topics"),
    ]

    operations = [
        migrations.AddField(
            model_name="topics",
            name="url",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
