# Generated by Django 5.0.6 on 2024-07-14 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_publication_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='slug',
        ),
    ]
